// food-recipes-validate.http
### create - invalid
POST http://localhost:3000/food-recipes
Content-Type: application/json

{
  "name": "Fried Rice",
  "description": "Savory rice dish with vegetables.",
  "ingredient": "Cooked rice, egg, peas, carrots, soy sauce",
  "instruction": "Fry all ingredients in a wok.",
  "imageUrl": "https://foodish-api.com/images/rice/rice18.jpg",
  "cookingDurationId": 2,
  "difficultyId": "A"
}

### update - invalid - url
PATCH http://localhost:3000/food-recipes/3
Content-Type: application/json

{
    "name": 100,
    "imageUrl": "https//foodish-api.com/images/rice/rice19.jpg"
}

### update - invalid path var
PATCH http://localhost:3000/food-recipes/A
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}

### get - invalid
GET http://localhost:3000/food-recipes/A

### delete - invalid
DELETE http://localhost:3000/food-recipes/A


###
### validate DB
###
### update - existing id
PATCH http://localhost:3000/food-recipes/999
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}