// food-recipes.http
### list
GET http://localhost:3000/food-recipes

### create
POST http://localhost:3000/food-recipes
Content-Type: application/json

{
  "name": "Spaghetti",
  "description": "A classic Italian pasta dish.",
  "ingredient": "Spaghetti, Tomato Sauce, Garlic, Olive Oil",
  "instruction": "Cook spaghetti, heat sauce, mix together.",
  "imageUrl": "",
  "difficultyId": 1,
  "cookingDurationId": 2
}