// food-recipes.rating.http
### u104 login
# @name u104
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "u104",
    "password": "changeit"
}

### case: u104 rating
# @ref u104
PUT  http://localhost:3000/api/v1/food-recipes/9/rating
Authorization: Bearer {{u104.accessToken}}
Content-Type: application/json

{
  "score": 4
}


### u105 login
# @name u105
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "u105",
    "password": "changeit"
}

### case: u105 rating
# @ref u105
PUT  http://localhost:3000/api/v1/food-recipes/9/rating
Authorization: Bearer {{u105.accessToken}}
Content-Type: application/json

{
  "score": 5
}


### case: view food-recipes 9
GET  http://localhost:3000/api/v1/food-recipes/9