// food-recipes.update.validate.http
### login
# @name u105
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "u105",
    "password": "changeit"
}

### case: update success
# @ref u105
PATCH http://localhost:3000/api/v1/food-recipes/2
Authorization: Bearer {{u105.accessToken}}
Content-Type: application/json

{
  "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}

### case: invalid url format
# @ref u105
PATCH http://localhost:3000/api/v1/food-recipes/2
Authorization: Bearer {{u105.accessToken}}
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https//foodish-api.com/images/rice/rice19.jpg"
}

### case: invalid path variable type
# @ref u105
PATCH http://localhost:3000/api/v1/food-recipes/A
Authorization: Bearer {{u105.accessToken}}
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}