// food-recipes.update.http

### auth login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "u101",
    "password": "changeit"
}

###
@accessToken = {{login.response.body.accessToken}}

### update
PATCH http://localhost:3000/food-recipes/19
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}

### update own
PATCH http://localhost:3000/food-recipes/11
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}


### update - invalid url format
PATCH http://localhost:3000/food-recipes/6
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https//foodish-api.com/images/rice/rice18.jpg"
}

### update - invalid path variable type
PATCH http://localhost:3000/food-recipes/A
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https://foodish-api.com/images/rice/rice19.jpg"
}

### update - not found id
PATCH http://localhost:3000/food-recipes/999
Content-Type: application/json

{
    "name": "Super Fried Rice !!",
    "imageUrl": "https://foodish-api.com/images/rice/rice18.jpg"
}
