// food-recipes.read.http
### list
GET http://localhost:3000/food-recipes


### get
GET http://localhost:3000/food-recipes/19

### search
GET http://localhost:3000/food-recipes/search?page[limit]=10&page[offset]=1

### search page 1
GET http://localhost:3000/food-recipes/search?page=1&limit=5


### search page 2
GET http://localhost:3000/food-recipes/search?page=2&limit=5


### search page 3
GET http://localhost:3000/food-recipes/search?page=A