// users.create.validate.http
### case: username is null
POST /users
Content-Type: application/json

{
    "username": null,
    "password": "changeit",
    "role": "USER"
}

### case: no username
POST /users
Content-Type: application/json

{
    "password": "changeit",
    "role": "USER"
}

### case: blank username
POST /users
Content-Type: application/json

{
    "username": "",
    "password": "changeit",
    "role": "USER"
}