// logged-users.http
### auth login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "u101",
    "password": "changeit"
}

###
@accessToken = {{login.response.body.accessToken}}


### get with valid token
GET http://localhost:3000/users/u101
Authorization: Bearer {{accessToken}}