# users.http
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1001",
    "password": "changeit",
    "role": "USER"
}


### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "a1101",
    "password": "changeit",
    "role": "ADMIN"
}