###
GET http://localhost:3000/food-recipes/search

###
GET http://localhost:3000/food-recipes/search?page=1&limit=5


###
GET http://localhost:3000/food-recipes/search?page=1&limit=5&mine=true



###
GET http://localhost:3000/food-recipes/paginate?page=1&limit=5



GET http://localhost:3000/food-recipes/search?name=ke&sort=desc

###
GET http://localhost:3000/food-recipes


###
POST http://localhost:3000/food-recipes
Content-Type: application/json

{
  "name": "Spaghetti",
  "description": "A classic Italian pasta dish.",
  "ingredient": "Spaghetti, Tomato Sauce, Garlic, Olive Oil",
  "instruction": "Cook spaghetti, heat sauce, mix together.",
  "difficulty": {
    "id": 2
  },
  "cookingDurationId": 1,
  "imageUrl": ""
}


###
GET http://localhost:3000/food-recipes/27


###
PATCH http://localhost:3000/food-recipes/27
Content-Type: application/json

{
  "name": "Spaghetti",
  "description": "A classic Italian pasta dish.",
  "ingredient": "Spaghetti, Tomato Sauce, Garlic, Olive Oil",
  "instruction": "Cook spaghetti, heat sauce, mix together.",
  "difficulty": {
    "id": 3
  },
  "cookingDurationId": 1,
  "imageUrl": ""
}

###
DELETE http://localhost:3000/food-recipes/26


###
POST http://localhost:3000/food-recipes
Content-Type: application/json

{
  "name": "Spaghetti",
  "description": "A classic Italian pasta dish.",
  "ingredient": "Spaghetti, Tomato Sauce, Garlic, Olive Oil",
  "instruction": "Cook spaghetti, heat sauce, mix together.",
  "difficulty": {
    "id": 2
  },
  "cookingDurationId": 1,
  "imageUrl": "",
  "user": {
    "id": "e2290114-a344-46db-ad56-c70e41d03465"
  }
}